config/routes.rb
Rails.application.routes.draw do
  get 'tasks/react'
  get 'tasks/offer'
  get 'tasks/edit'
  get 'tasks/tasks_data'
  get 'tasks/test'
  get 'tasks/task'
  get 'tasks/offer_results'

  post 'tasks/offer_create', to: 'tasks#offer_create'
  post 'tasks/positive_offer', to: 'tasks#positive_offer'
  post 'tasks/negative_offer', to: 'tasks#negative_offer'
  post 'tasks/delete_task', to: 'tasks#delete_task'
  post 'tasks/test_answer', to: 'tasks#test_answer'
  post 'tasks/task_answer', to: 'tasks#task_answer'

  get 'users/create'
  get 'users/reset'
  get 'users/destroy'
  get 'users/new'

  get 'users/profile'
  get 'users/rating'
  get 'users/withdrawal'
  get 'users/users_data'

  get 'users/competition_speech'
  get 'users/competition_productivity'
  get 'users/competition_sleep'
  get 'users/competition_nutrition'

  post 'users/change_sphere', to: 'users#change_sphere'
  post 'users/cash_check', to: 'users#cash_check'
  post 'users/new_password', to: 'users#new_password'
  post 'users/create', to: 'users#create'
  post 'users/destroy', to: 'users#destroy'

  get 'sessions/create'
  get 'sessions/destroy'
  get 'sessions/new'
  post 'sessions/create', to: 'sessions#create'
  post 'sessions/destroy', to: 'sessions#destroy'

  get 'main/input'

  root 'main#input', as: 'home'

  resources :sessions
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start text-black">
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-2">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-3 mx-auto mb-2">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>OSSIF
          </h6>
          <p>
            Там, где кончается саморазвитие, начинается диван.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-2">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Контакты</h6>
          <p><i class="fas fa-home me-3"></i> Москва, Пресненская набережная, 12.</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            sashabukhov2@yandex.ru
          </p>
          <p><i class="fas fa-phone me-3"></i> + 7 985 492 47 70</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: #00CED1;">
    © 2023 Copyright: OSSIF
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg" class="navbar">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if session[:user_id].nil? %>
          <li class="nav-item">
              <%= link_to 'OSSIF', '/main/input', class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Вход', '/sessions/new', class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Регистрация', '/users/new', class: 'nav-link active' %>
          </li>
        <% elsif User.find(session[:user_id]).superuser %>
          <li class="nav-item">
              <%= link_to 'Пользователи', '/users/users_data', class: 'nav-link active' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Рейтинги', '/users/rating', class: 'nav-link active' %>
          </li>
          <div class="dropdown">
            <button class="btn btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              Соревнования
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li class="nav-item">
                  <%= link_to 'Речь', '/users/competition_speech', class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Эффективность', '/users/competition_productivity', class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Сон', '/users/competition_sleep', class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Питание', '/users/competition_nutrition', class: 'nav-link active' %>
              </li>
            </ul>
          </div>
          <li class="nav-item">
              <%= link_to 'Задания', '/tasks/tasks_data', class: 'nav-link active' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Редактирование', '/tasks/edit', class: 'nav-link active' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Обработка предложений заданий', '/tasks/react', class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Выход', sessions_destroy_path, data: {turbo_method: :delete}, class: 'nav-link active' %>
          </li>
        <% else %>
          <% if !User.find(session[:user_id]).tested %>
          <li class="nav-item">
              <%= link_to 'Тестирование', '/tasks/test', class: 'nav-link active' %>
          </li>
          <% end %>
          <% if User.find(session[:user_id]).tested %>
          <li class="nav-item">
              <%= link_to 'Задания', '/tasks/task', class: 'nav-link active' %>
          </li>
          <% end %>
          <% if User.find(session[:user_id]).rating > 1000 %>
          <li class="nav-item">
              <%= link_to 'Предложить задание', '/tasks/offer', class: 'nav-link active' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Предложенные задания', '/tasks/offer_results', class: 'nav-link active' %>
          </li>
          <% end %>
          <div class="dropdown">
            <button class="btn btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              Соревнования
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li class="nav-item">
                  <%= link_to 'Речь', '/users/competition_speech', class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Эффективность', '/users/competition_productivity', class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Сон', '/users/competition_sleep', class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Питание', '/users/competition_nutrition', class: 'nav-link active' %>
              </li>
            </ul>
          </div>
          <li class="nav-item">
              <%= link_to 'Рейтинги', '/users/rating', class: 'nav-link active' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Профиль', '/users/profile', class: 'nav-link active' %>
          </li>
          <% if User.find(session[:user_id]).rating > 1000 %>
          <li class="nav-item">
              <%= link_to 'Вывод средств', '/users/withdrawal', class: 'nav-link active' %>
          </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Выход', sessions_destroy_path, data: {turbo_method: :delete}, class: 'nav-link active' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OSSIF</title>
    <%# <%= favicon_link_tag '#' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
      .nav-link:hover {
         background: #20B2AA; /* Цвет блока при наведении курсора. */
         color: white;  /* Цвет текста при наведении курсора. */
      }
      body {
        background: #00FFFF;
        margin: 0;
        display: flex;
        flex-direction: column;
        min-height: 100vh;
      }
      main {
        /* Чтобы занимал оставшееся пространство */
        flex-grow: 1;
      }
      .navbar {
        background: #00CED1;
      }
      footer {
        background: #B0E0E6;
        flex-shrink: 0;
      }
    </style>
<%#
    <script language="JavaScript">
    function expandit(id){
      obj = document.getElementById(id);
      if (obj.style.display=="none") obj.style.display="";
      else obj.style.display="none";
    }
    </script>
%>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <br/>
    <main role="main">
      <div class="container">
        <% flash.each do |type, msg| %>
          <% if type == 'success' %>
            <div class="alert alert-success">
              <%= msg %>
            </div>
          <% elsif type == 'warning' %>
            <div class="alert alert-danger">
              <%= msg %>
            </div>
          <% end %>
        <% end %>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>